name: test path
on:
  workflow_dispatch:
    inputs:
      DEBUG_MODE:
        description: DEBUG_MODE
        default: 'no'

jobs:
  test_path:
    name: test_path-${{ matrix.job.cfg }}-${{ matrix.job.type }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { cfg: lin, type: 'zip'   , os: ubuntu-latest  }
          - { cfg: win, type: 'zip'   , os: windows-latest }
          - { cfg: mac, type: 'zip'   , os: macos-latest   }
          - { cfg: lin, type: 'tar.xz', os: ubuntu-latest  }
          - { cfg: win, type: 'tar.xz', os: windows-latest }
          - { cfg: mac, type: 'tar.xz', os: macos-latest   }
    steps:
      - name: checkout
        uses: deep-soft/checkout@v3

      - name: create test directory and file
        shell: bash
        run: |
          mkdir TestDir
          pushd TestDir
          echo "a" > "a"
          echo "b" > "b"
          echo "TestFile" > "TestFile"
          echo "TestFile2" > "TestFile2"
          echo "TestFile.exe" > "TestFile.exe"
          echo "someotherfile" > "someotherfile"
          echo "someotherfile2" > "someotherfile2"
          popd

      - uses: deep-soft/zip-release@main
        with:
          type: "${{ matrix.job.type }}"
          filename: 'tst-path-${{ matrix.job.type }}-${{ matrix.job.cfg }}.${{ matrix.job.type }}'
          directory: TestDir
          path: "TestFile*"
          #inclusions: 'a'
          #exclusions: 'someotherfile*'
          verbose: ${{ inputs.DEBUG_MODE }}
          debug: ${{ inputs.DEBUG_MODE }}

      - name: test lin / mac
        if: ${{ matrix.job.cfg == 'lin' || matrix.job.cfg == 'mac' }}
        shell: bash
        run: |
          if [[ ${{ matrix.job.type }} == 'zip' ]]; then
            unzip -t ${{ env.ZIP_RELEASE_ARCHIVE }}
          else
            xz -tv ${{ env.ZIP_RELEASE_ARCHIVE }}
            tar -tf ${{ env.ZIP_RELEASE_ARCHIVE }}
          fi

      - name: test win
        if: ${{ matrix.job.cfg == 'win' }}
        shell: bash
        run: |
          7z t ${{ env.ZIP_RELEASE_ARCHIVE }}
