name: test download
on:
  workflow_dispatch:

jobs:
  test_download:
    name: test_download-${{ matrix.job.cfg }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { cfg: lin, os: ubuntu-latest  }
          - { cfg: win, os: windows-latest }
          - { cfg: mac, os: macos-latest   }
    steps:
      - name: checkout
        uses: deep-soft/checkout@v3

      - name: test download
        shell: bash
        run: |
          name_common=$(cat bin/bin-common.txt);
          name_7z=$(cat bin/bin-${{ matrix.job.cfg }}.txt);
          echo $name_common;
          echo $name_7z;
          #curl refs/tags/bins/$name_7z -o $name_7z;
          mkdir tmp
          pushd tmp
          echo "curl -LOJ $name_common$name_7z;"
          curl -LOJ $name_common$name_7z;
          # name_7z_full=$(find . -type f -name $name_7z -print0 | xargs -0 realpath)
          name_7z_full=$(find . -name "$name_7z" | xargs readlink -f)
          echo "name_7z_full=$name_7z_full" >> $GITHUB_ENV
          echo "list: pushd"
          ls -l
          popd
          echo "list: popd"
          ls -l
      
      - name: test unpack
        shell: bash
        run: |
          pushd tmp
          echo "name_7z_full: ${{ env.name_7z_full }}"
          file "${{ env.name_7z_full }}"
          xz -vt "${{ env.name_7z_full }}"
          # if [ "${{ matrix.job.cfg }}" == "win" ]; then
          #   xz -9 ${{ env.name_7z_full }}
          #   name_xz_full=$(find . -name "*.xz" | xargs readlink -f)
          #   ls -l $name_xz_full
          #   echo "name_xz_full=$name_xz_full" >> $GITHUB_ENV            
          # else
          #   xz -vt "${{ env.name_7z_full }}"
          # fi
          popd

#      - name: Upload Artifact
#        if: ${{ matrix.job.cfg == 'win' }}
#        uses: deep-soft/upload-artifact@v3
#        with:
#          name: xz
#          path: |
#            ${{ env.name_xz_full }}
#            tmp

  test_arc:
    name: test_arc-${{ matrix.job.cfg }}-${{ matrix.job.type }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { cfg: lin, type: 'zip'   , os: ubuntu-latest  }
          - { cfg: win, type: 'zip'   , os: windows-latest }
          - { cfg: mac, type: 'zip'   , os: macos-latest   }
          - { cfg: lin, type: 'tar.xz', os: ubuntu-latest  }
          - { cfg: win, type: 'tar.xz', os: windows-latest }
          - { cfg: mac, type: 'tar.xz', os: macos-latest   }
    steps:
      - name: checkout
        uses: deep-soft/checkout@v3

      - uses: deep-soft/zip-release@main
        with:
          type: "${{ matrix.job.type }}"
          filename: 'tst-${{ matrix.job.type }}-${{ matrix.job.cfg }}.${{ matrix.job.type }}'

      - name: test lin / mac
        if: ${{ matrix.job.cfg == 'lin' || matrix.job.cfg == 'mac' }}
        shell: bash
        run: |
          if [[ ${{ matrix.job.type }} == 'zip' ]]; then
            unzip -t ${{ env.ZIP_RELEASE_ARCHIVE }}
          else
            xz -tv ${{ env.ZIP_RELEASE_ARCHIVE }}
          fi

      - name: test win
        if: ${{ matrix.job.cfg == 'win' }}
        shell: bash
        run: |
          7z t ${{ env.ZIP_RELEASE_ARCHIVE }}

  test_path:
    name: test_path-${{ matrix.job.cfg }}-${{ matrix.job.type }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { cfg: lin, type: 'zip'   , os: ubuntu-latest  }
          - { cfg: win, type: 'zip'   , os: windows-latest }
          - { cfg: mac, type: 'zip'   , os: macos-latest   }
          - { cfg: lin, type: 'tar.xz', os: ubuntu-latest  }
          - { cfg: win, type: 'tar.xz', os: windows-latest }
          - { cfg: mac, type: 'tar.xz', os: macos-latest   }
    steps:
      - name: checkout
        uses: deep-soft/checkout@v3

      - name: create test directory and file
        shell: bash
        run: |
          mkdir TestDir
          pushd TestDir
          echo "TestFile" > TestFile
          echo "TestFile2" > TestFile2
          echo "TestFile.exe" > TestFile.exe
          popd

      - uses: deep-soft/zip-release@main
        with:
          type: "${{ matrix.job.type }}"
          filename: 'tst-path-${{ matrix.job.type }}-${{ matrix.job.cfg }}.${{ matrix.job.type }}'
          directory: TestDir
          verbose: "yes"
          path: "TestFile*"

      - name: test lin / mac
        if: ${{ matrix.job.cfg == 'lin' || matrix.job.cfg == 'mac' }}
        shell: bash
        run: |
          if [[ ${{ matrix.job.type }} == 'zip' ]]; then
            unzip -t ${{ env.ZIP_RELEASE_ARCHIVE }}
          else
            xz -tv ${{ env.ZIP_RELEASE_ARCHIVE }}
          fi

      - name: test win
        if: ${{ matrix.job.cfg == 'win' }}
        shell: bash
        run: |
          7z t ${{ env.ZIP_RELEASE_ARCHIVE }}
