name: test download
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: deep-soft/checkout@v3

      - name: test
        shell: bash
        run: |
          name_7z=$(cat bin/bin-lin.txt);
          echo $name_7z;
          #curl refs/tags/bins/$name_7z -o $name_7z;
          curl -o $name_7z https://github.com/deep-soft/zip-release/releases/download/bins/$name_7z;
          ls -l
      

    
