name: test download
on:
  workflow_dispatch:

jobs:
  test_download:
    name: test_download-${{ matrix.job.cfg }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { cfg: lin, os: ubuntu-latest  }
          - { cfg: win, os: windows-latest }
          - { cfg: mac, os: macos-latest   }
    steps:
      - name: checkout
        uses: deep-soft/checkout@v3

      - name: test download
        shell: bash
        run: |
          name_common=$(cat bin/bin-common.txt);
          name_7z=$(cat bin/bin-${{ matrix.job.cfg }}.txt);
          echo $name_common;
          echo $name_7z;
          #curl refs/tags/bins/$name_7z -o $name_7z;
          mkdir tmp
          pushd tmp
          echo "curl -LOJ $name_common$name_7z;"
          curl -LOJ $name_common$name_7z;
          # name_7z_full=$(find . -type f -name $name_7z -print0 | xargs -0 realpath)
          name_7z_full=$(find . -name "$name_7z" | xargs readlink -f)
          echo "name_7z_full=$name_7z_full" >> $GITHUB_ENV
          echo "list: pushd"
          ls -l
          popd
          echo "list: popd"
          ls -l
      
      - name: test unpack
        shell: bash
        run: |
          echo "name_7z_full: ${{ env.name_7z_full }}"
          file "${{ env.name_7z_full }}"
          xz -vt "${{ env.name_7z_full }}"

  test_zip:
    name: test_zip-${{ matrix.job.cfg }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { cfg: lin, os: ubuntu-latest  }
          - { cfg: win, os: windows-latest }
          - { cfg: mac, os: macos-latest   }
    steps:
      - name: checkout
        uses: deep-soft/checkout@v3

      - uses: deep-soft/zip-release@main
        with:
          type: "zip"
          filename: 'tst-zip-${{ matrix.job.cfg }}.zip'

      - name: test lin / mac
        if: ${{ matrix.job.cfg == 'lin' || matrix.job.cfg == 'mac' }}
        shell: bash
        run: |
          unzip -t ${{ env.ZIP_RELEASE_ARCHIVE }}

      - name: test win
        if: ${{ matrix.job.cfg == 'win' }}
        shell: bash
        run: |
          7z t ${{ env.ZIP_RELEASE_ARCHIVE }}
