name: test download
on:
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.job.cfg }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { cfg: lin, os: ubuntu-latest  }
          - { cfg: win, os: windows-latest }
          - { cfg: mac, os: macos-latest   }
    steps:
      - name: checkout
        uses: deep-soft/checkout@v3

      - name: test download
        shell: bash
        run: |
          name_7z=$(cat bin/bin-${{ matrix.job.cfg }}.txt);
          echo $name_7z;
          #curl refs/tags/bins/$name_7z -o $name_7z;
          mkdir tmp
          pushd tmp
          curl -o $name_7z https://github.com/deep-soft/zip-release/releases/download/bins/$name_7z;
          # name_7z_full=$(find . -type f -name $name_7z -print0 | xargs -0 realpath)
          name_7z_full=$(find . -name "$name_7z" | xargs readlink -f)
          echo "name_7z_full=$name_7z_full" >> $GITHUB_ENV
          echo "list: pushd"
          ls -l
          popd
          echo "list: popd"
          ls -l
      
      - name: test unpack
        shell: bash
        run: |
          echo "name_7z_full: ${{ env.name_7z_full }}"
